### ISSUE TITLE
Return the PR object instead of simply its number

### ISSUE THREAD

**Issue by tlvenn** [jwalton/gh-find-current-pr#1]
Hi,

I believe this action would be a lot more useful if it would return the entire PR that is fetched instead of simply returning its number.

For some context, I found this action while I was searching for one to get the title of the current PR.

It would also align better with the action name ;)

**Comment by jwalton** [comment]
Can you return a complex object as an output?  :P  That'd be cool if we can do it.  I'm pretty sure inputs are limited to strings, so I just assumed outputs were, too.

**Comment by tlvenn** [comment]
Ha yes good point, can we update the action outputs to have some basic info such as:
- `number`
- `title`
- `body`
- `state`
- `locked`

**Comment by tlvenn** [comment]
I have contributed a small PR to add `number`, `title` and `body` outputs. I have kept `pr` for backward compatibility but deprecated the output in the yaml file.

**Comment by jwalton** [comment]
Released as v1.0.2.
