### ISSUE TITLE
not triggered by `pull_request_target`

### ISSUE THREAD

**Issue by AngryMaciek** [jwalton/gh-find-current-pr#111]
When I specify event type `pull_request` everything works fine; however, on `pull_request_target` the step is not recognised by the CI (as if it was not in the YAML); that sucks, since PRs from other forks wont get comments on the first event type...

**Comment by jwalton** [comment]
I’m more than happy to accept a PR that fixes this.

**Comment by AngryMaciek** [comment]
I think I made a mistake there... obviously, when you run a workflow on `pull_request_target` you run in the context of the base branch so any changes you introduce on head branch wont be considered... I think you can close this...
