### ISSUE TITLE
Receive deprecated warnings at GH workflow step 

### ISSUE THREAD

**Issue by hitenshkharva11** [jwalton/gh-find-current-pr#113]
Warning: The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Expected behavior
New version of this repo will fix the warnings list that we get in GH action run ?

Please find the bug below:

<img width="711" alt="image" src="https://github.com/jwalton/gh-find-current-pr/assets/108146780/fae2764e-f9be-4419-af35-a48ab36482e9">

**Comment by jwalton** [comment]
Please upgrade to v1.3.2.
