### ISSUE TITLE
Returns unexpected PR number when multiple PRs including same commit

### ISSUE THREAD

**Issue by ryokkkke** [jwalton/gh-find-current-pr#18]
Thanks for your work of this library!

This issue says, for instance, when there are three PRs like this:

- PR `#1`: commit a
- PR `#2`: commit a -> commit b
- PR `#3`: commit a -> commit b -> commit c

I pass each last commit's sha to gh-find-current-pr, but each all actions return number `#3`.

method `octokit.rest.repos.listPullRequestsAssociatedWithCommit()` returns `[3,2,1]` but code `prs[0]` in main.js always returns 3.
Actually I'm not sure the order of the array returned though, but in my case, always returns last PR's number.

(official doc: https://octokit.github.io/rest.js/v18#repos-list-pull-requests-associated-with-commit)

**Comment by jwalton** [comment]
One thing I can see doing is trying to find a PR in the `prs` array that matches the commit exactly...

**Comment by warpech** [comment]
In fact, `octokit.rest.repos.listPullRequestsAssociatedWithCommit()` sometimes finds PRs that don't event match the commit and **puts wrong results first**. See my comment: https://github.com/handsontable/handsontable/issues/9678#issuecomment-1185817007
