### ISSUE TITLE
Richer outputs

### ISSUE THREAD

**Issue by guioconnor** [jwalton/gh-find-current-pr#19]
Hi, thanks for this handy action, it's been very useful for us.

However, for us we need to know whether the PR is a draft or not.

Of course we, can get the PR number and make a further request for the PR metadata, but since the information is already on the first request, it's wasteful.

I forked your repo and and made the following change. 

https://github.com/guioconnor/gh-find-current-pr/blob/master/main.js#L21

I wonder if you'd take a pull request so this is available for everyone and avoids me hosting it separately. 

Also, perhaps there are other properties that's worth including instead of doing piecemeal work.

**Comment by jwalton** [comment]
For sure I'd take a PR.

**Comment by guioconnor** [comment]
@jwalton Great, thanks. Here's the PR

https://github.com/jwalton/gh-find-current-pr/pull/20

If you think other properties are equally worthy of output for a more general solution, I'm happy to update the PR to reflect that.

**Comment by guioconnor** [comment]
Hi @jwalton , I wonder if you had a chance to look at the PR.

**Comment by guioconnor** [comment]
Awesome, thank you.
