### ISSUE TITLE
Make sure the returned PR is open

### ISSUE THREAD

**Issue by tlvenn** [jwalton/gh-find-current-pr#2]
The API used (`client.repos.listPullRequestsAssociatedWithCommit`) will include open and closed pull requests, the action should only return an open pull request.

**Comment by tlvenn** [comment]
@jwalton what is your though on this one ? Right now the action return the first result but i am wondering if for example if given N results (N > 1) if it should not return the first one that is open and ultimately return the first one if all are closed.

**Comment by jwalton** [comment]
Yes, that sounds reasonable to me. You're generally after an open one.  I suppose if there are multiple open ones it should return the most recently opened one?
