### ISSUE TITLE
Update action to use updated version of Node

### ISSUE THREAD

**Issue by jjoynson-iw** [jwalton/gh-find-current-pr#25]
Seeing the following warning message when using this action:
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: jwalton/gh-find-current-pr
```

Looks like the version is set here: https://github.com/jwalton/gh-find-current-pr/blob/master/action.yml#L27

**Comment by jwalton** [comment]
Thanks for the heads up!  I'll update this sometime this week.  I've been wanting to migrate this to TypeScript too - see if I can do that at the same time.
