### ISSUE TITLE
The `set-output` command is deprecated, upgrade to Env files

### ISSUE THREAD

**Issue by Sophie1142** [jwalton/gh-find-current-pr#51]
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/43194894/200671733-a6e9e00e-eb66-42ee-8809-0504f6adbc0c.png">

**Comment by jwalton** [comment]
Are you using the latest?  This should be fixed already, as we’re using @actions/core ^1.10.0, which doesn’t set outputs via the old stdout method.

**Comment by jwalton** [comment]
Oh, I see from your screen shot you’re on 1.3.0.  Can you upgrade to 1.3.2 and verify this is fixed?

**Comment by jwalton** [comment]
I’ll close this for now - if you have further problems feel free to open another issue.
