### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by muiriswoulfe** [jwalton/gh-find-current-pr#93]
The action outputs the following on each build:

```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

The code should be changed to resolve this issue and prevent the tool being impacted by the deprecation.

**Comment by jwalton** [comment]
Hi @muiriswoulfe.  This issue should already be fixed.  What version of the action are you running?  Does this problem go away if you upgrade to v1.3.2?

**Comment by muiriswoulfe** [comment]
Thanks @jwalton. That did fix the problem.

The reason I wasn't using the newer version is because it seems v1.3.2 isn't published to the GitHub Marketplace at <https://github.com/marketplace/actions/find-current-pull-request>. I'm still able to use the newer version, but it would be good to get it published so that others can more immediately use it.

**Comment by jwalton** [comment]
Oh!  Thanks for the heads up!  I'm using semantic-release, but I guess it doesn't automatically update the marketplace.  I wonder how many other github actions I have published that need fixing?  O_o
